language: csharp
dotnet: 2.1.502
mono: none
os: linux
dist: xenial
sudo: enabled
before_install:
  - chmod +x build.sh
script:
  - "./build.sh"
env:
  - RESULTFUL_PACKAGE_VERSION: 0.0.1-beta01
  - UNION_PACKAGE_VERSION: 0.0.1-beta01
  - ONE_OF_PACKAGE_VERSION: 0.0.1-beta01
branches:
  only:
    - master
    - develop
